# Generated by Django 3.2 on 2021-04-26 21:44

import PlanIlan.models.teacher
import PlanIlan.storage
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('syllabus_link', models.URLField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not fall short of 0'), django.core.validators.MaxValueValidator(5, 'Value should not exceed 5')])),
                ('amount_of_raters', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'amount of raters should be a natural number')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('office', models.CharField(max_length=100, null=True)),
                ('website_url', models.URLField(null=True)),
                ('image', models.ImageField(null=True, storage=PlanIlan.storage.OverwriteStorage(), upload_to=PlanIlan.models.teacher.user_directory_path)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='PlanIlan.faculty')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='PlanIlan.rating')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(editable=False, max_length=254, unique=True)),
                ('faculty', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='PlanIlan.faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='TeacherPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('amount_of_likes', models.IntegerField(default=0)),
                ('headline', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanIlan.user')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='PlanIlan.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='PlanIlan.title'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=80)),
                ('building_number', models.IntegerField(blank=True, null=True)),
                ('class_number', models.IntegerField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('building_name', 'building_number', 'class_number', 'online')},
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('year', models.PositiveSmallIntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_times', to='PlanIlan.day')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_times', to='PlanIlan.semester')),
            ],
            options={
                'unique_together': {('day', 'semester', 'start_time', 'end_time', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=3)),
                ('details_link', models.URLField(null=True)),
                ('points', models.FloatField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='PlanIlan.course')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='PlanIlan.lessontype')),
                ('locations', models.ManyToManyField(related_name='lessons', to='PlanIlan.Location')),
                ('session_times', models.ManyToManyField(related_name='lessons', to='PlanIlan.LessonTime')),
                ('teachers', models.ManyToManyField(related_name='lessons', to='PlanIlan.Teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamPeriod',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='PlanIlan.examperiod')),
            ],
            options={
                'unique_together': {('period', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='CoursePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('amount_of_likes', models.IntegerField(default=0)),
                ('headline', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanIlan.user')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='PlanIlan.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='PlanIlan.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='exams',
            field=models.ManyToManyField(related_name='courses', to='PlanIlan.Exam'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='PlanIlan.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='PlanIlan.rating'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('name', 'title')},
        ),
    ]
