# Generated by Django 3.1.5 on 2021-03-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('period', 'date', 'course')},
        ),
    ]
