# Generated by Django 3.2 on 2021-05-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIlan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='email address'),
        ),
    ]
