# Generated by Django 3.1.5 on 2021-04-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average',
            field=models.FloatField(default=None, null=True),
        ),
    ]
