# Generated by Django 3.0.5 on 2020-12-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='building_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='class_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
