# Generated by Django 3.1.4 on 2020-12-08 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIlan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher_name',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.IntegerField(choices=[(89, 'למדעי המחשב'), (272, 'מדעי המוח'), (275, 'מדעי המוח לתארים מתקדמים'), (36, 'המחלקה לערבית'), (82, 'אופטימטריה'), (55, 'המחלקה לניהול'), (70, 'מינהל עסקים'), (63, 'ביה"ס לתקשורת'), (77, 'חינוך'), (94, 'דיפלומה'), (5, 'המדרשה לנשים'), (66, 'כלכלה'), (10, 'תושב"ע'), (74, 'מדעי החברה'), (84, 'כימיה'), (75, 'גיאוגרפיה'), (79, 'הוראה'), (25, 'תכנית ברוקדייל'), (273, 'לימודי מגדר'), (43, 'המחלקה לתרבות צרפת'), (81, 'הפקולטה לרפואה'), (99, 'הפקולטה למשפטים'), (72, 'המכון לשלטון מקומי'), (54, 'מדעי הרוח'), (93, 'רב תחומי'), (76, 'עבודה סוציאלית'), (17, 'מדעי היהדות'), (41, 'אנגלית כשפה זרה'), (6, 'הבעה אקדמית ואולפן'), (21, 'אמנות יהודית'), (37, 'בלשנות וספרות אנגלית'), (18, 'הסטוריה כללית'), (16, 'לימודי ארץ ישראל וארכיאולוגיה'), (19, 'מזרח התיכון'), (46, 'לימודים קלאסיים'), (12, 'המחלקה ללשון עברית וללשונות שמיות'), (71, 'מדעי המדינה'), (35, 'מדעי המידע'), (47, 'מוסיקה'), (30, 'מחשבת ישראל'), (88, 'מתמטיקה'), (64, 'סוציולוגיה ואנתרופולוגיה'), (33, 'ספרות'), (13, 'ספרות עם ישראל'), (31, 'פילוסופיה'), (86, 'פיסיקה'), (60, 'פסיכולוגיה'), (73, 'קרימינולוגיה'), (11, 'תולדות ישראל ויהדות זמננו'), (9, 'תלמוד ותושב"ע'), (8, 'תנ"ך'), (50, 'תרגום וחקר התרגום'), (83, 'הנדסה'), (80, 'מדעי החיים'), (3, 'פילוסופיה יהודית'), (4, 'לימודי יסוד - תולדות ישראל'), (2, 'לימודי יסוד - תלמוד'), (1, 'לימודי יסוד - תנ"ך'), (27, 'לימודי פרשנות ותרבות'), (22, 'לימודי תעודה בעריכה'), (-1, 'לא קיים')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, "סמסטר א'"), (2, "סמסטר ב'"), (3, 'שנתי')]),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='average',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not fall short of 0'), django.core.validators.MaxValueValidator(5, 'Value should not exceed 5')]),
        ),
        migrations.AlterField(
            model_name='teacherrating',
            name='average',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not fall short of 0'), django.core.validators.MaxValueValidator(5, 'Value should not exceed 5')]),
        ),
    ]
