# Generated by Django 3.0.5 on 2020-12-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIlan', '0002_auto_20201229_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.IntegerField(choices=[(0, 'ד"ר'), (1, "פרופ'"), (2, 'מר'), (3, 'גברת'), (4, 'הרב'), (-1, '')]),
        ),
    ]
