# Generated by Django 3.2 on 2021-04-21 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIlan', '0002_auto_20210420_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not fall short of 0'), django.core.validators.MaxValueValidator(5, 'Value should not exceed 5')]),
        ),
    ]
