# Generated by Django 3.1.5 on 2021-04-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIlan', '0003_auto_20210413_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='_faculty',
            field=models.IntegerField(choices=[(0, 'כללי'), (1, 'מדעי החיים '), (2, 'מדעי היהדות'), (3, 'משפטים'), (4, 'רפואה'), (5, 'מדעי החברה'), (6, 'הנדסה '), (7, 'מדעים מדויקים'), (8, 'יחידה ללימודים בין תחומיים'), (9, 'מדעי הרוח'), (10, 'לא ידוע')], db_column='faculty', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='_title',
            field=models.IntegerField(choices=[(-1, ''), (0, 'ד"ר'), (1, "פרופ'"), (2, 'מר'), (3, 'גברת'), (4, 'הרב'), (5, 'עו"ד'), (6, 'השופט')], db_column='title'),
        ),
    ]
