# Generated by Django 3.1.5 on 2021-04-13 17:18

import PlanIlan.models.teacher
import PlanIlan.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIlan', '0005_auto_20210413_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, storage=PlanIlan.storage.OverwriteStorage(), upload_to=PlanIlan.models.teacher.user_directory_path),
        ),
    ]
