# Generated by Django 3.2 on 2021-06-18 14:06

from django.db import migrations, models
import django.db.models.deletion
import plan_ilan.apps.timetable_generator.models.timetable


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetablesolution',
            options={'ordering': ['-score', 'created', 'modified', 'pk'], 'verbose_name': 'solution'},
        ),
        migrations.RenameField(
            model_name='blockedtimeperiod',
            old_name='blocked_time_periods',
            new_name='times',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='elective_points_bound',
            field=models.ForeignKey(default=plan_ilan.apps.timetable_generator.models.timetable.get_default_elective_points_bound, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='timetable_generator.interval'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='max_num_of_days',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
