# Generated by Django 3.2 on 2021-06-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0005_alter_lesson_options'),
        ('timetable_generator', '0002_auto_20210618_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['common_info', 'created']},
        ),
        migrations.AlterModelOptions(
            name='timetablecommoninfo',
            options={'ordering': ['account', 'semester', 'name', 'pk']},
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='semester',
        ),
        migrations.AddField(
            model_name='timetablecommoninfo',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='common_info', to='web_site.semester'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='timetablecommoninfo',
            unique_together={('account', 'name', 'semester')},
        ),
    ]
