# Generated by Django 3.2 on 2021-05-16 18:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import plan_ilan.apps.web_site.models.review
import plan_ilan.apps.web_site.models.teacher
import plan_ilan.apps.web_site.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, null=True, unique=True, verbose_name='email address')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('syllabus_link', models.URLField(null=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'db_table': 'days',
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'db_table': 'faculties',
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=80)),
                ('text', models.TextField(max_length=5000)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.account')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_web_site.review_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('office', models.CharField(max_length=100, null=True)),
                ('website_url', models.URLField(null=True)),
                ('image', models.ImageField(null=True, storage=plan_ilan.apps.web_site.storage.OverwriteStorage(), upload_to=plan_ilan.apps.web_site.models.teacher.user_directory_path)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='web_site.faculty')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'db_table': 'titles',
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='TeacherRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not fall short of 0'), django.core.validators.MaxValueValidator(5, 'Value should not exceed 5')])),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='web_site.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.account')),
            ],
            options={
                'db_table': 'teacher_ratings',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='web_site.title'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'db_table': 'semesters',
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='web_site.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='web_site.account')),
            ],
            options={
                'db_table': 'replies',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=80)),
                ('building_number', models.IntegerField(blank=True, null=True)),
                ('class_number', models.IntegerField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'locations',
                'unique_together': {('building_name', 'building_number', 'class_number', 'online')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='web_site.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='web_site.account')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'db_table': 'lesson_types',
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('year', models.PositiveSmallIntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_times', to='web_site.day')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_times', to='web_site.semester')),
            ],
            options={
                'db_table': 'lesson_times',
                'unique_together': {('day', 'semester', 'start_time', 'end_time', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=3)),
                ('details_link', models.URLField(null=True)),
                ('points', models.FloatField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='web_site.course')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='web_site.lessontype')),
                ('locations', models.ManyToManyField(related_name='lessons', to='web_site.Location')),
                ('session_times', models.ManyToManyField(related_name='lessons', to='web_site.LessonTime')),
                ('teachers', models.ManyToManyField(related_name='lessons', to='web_site.Teacher')),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='ExamPeriod',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'db_table': 'exam_periods',
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='web_site.examperiod')),
            ],
            options={
                'db_table': 'exams',
                'unique_together': {('period', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('number', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(editable=False, max_length=60)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['number'],
                'abstract': False,
                'unique_together': {('number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not fall short of 0'), django.core.validators.MaxValueValidator(5, 'Value should not exceed 5')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='web_site.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.account')),
            ],
            options={
                'db_table': 'course_ratings',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='web_site.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='exams',
            field=models.ManyToManyField(related_name='courses', to='web_site.Exam'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='web_site.faculty'),
        ),
        migrations.AddField(
            model_name='account',
            name='faculty',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='web_site.faculty'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeacherReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_site.review')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='web_site.teacher')),
            ],
            options={
                'db_table': 'teacher_reviews',
            },
            bases=('web_site.review',),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('name', 'title')},
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_site.review')),
                ('image', models.ImageField(blank=True, default='course_average-1.jpg', null=True, upload_to=plan_ilan.apps.web_site.models.review.upload_location)),
                ('is_image_valid', models.BooleanField(default=False)),
                ('average', models.FloatField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='web_site.course')),
            ],
            options={
                'db_table': 'course_reviews',
            },
            bases=('web_site.review',),
        ),
    ]
