# Generated by Django 3.2 on 2021-05-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
