# Generated by Django 3.2 on 2021-05-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_auto_20210516_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['pk', 'faculty']},
        ),
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['period', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lessontime',
            options={'ordering': ['day', 'start_time', 'end_time']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['date_modified', 'date_created']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name', 'title', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='teacherreview',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='faculty',
        ),
        migrations.AddField(
            model_name='teacher',
            name='faculties',
            field=models.ManyToManyField(related_name='teachers', to='web_site.Faculty'),
        ),
    ]
