# Generated by Django 3.2 on 2021-06-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0004_auto_20210604_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['lesson_type', 'group']},
        ),
    ]
