# Generated by Django 3.2 on 2021-08-07 14:21

from django.db import migrations, models
import plan_ilan.apps.web_site.models.teacher


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0005_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to=plan_ilan.apps.web_site.models.teacher.user_directory_path),
        ),
    ]
